### ISSUE TITLE
[Improper parsing]: 

### ISSUE THREAD

**Issue by zagrosbingol** [doyensec/inql#119]
### InQL version

BApp Store

### GraphQL API

https://api.republik.ch/graphql

### What isn't working?

Hello, 

I have configured burp to use jython 2.3 and i am currently recieving the following error, when trying to fetch the introspection schema. The introspection is successful, however the issue is as the following:
- Not being displayed in inql scanner
- Recieving the following errors on the extension console:
```
Exception in thread Thread-8:Traceback (most recent call last):
  File "/home/zabiol/Desktop/tools/jython/jython-standalone-2.7.3.jar/Lib/threading.py", line 222, in _Thread__bootstrap
    self.run()
  File "/home/zabiol/Desktop/tools/jython/jython-standalone-2.7.3.jar/Lib/threading.py", line 213, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/tmpZDBAHx/inql/utils.py", line 237, in async_run
  File "/tmp/tmpZDBAHx/inql/widgets/generator.py", line 316, in async_run
  File "/tmp/tmpZDBAHx/inql/introspection.py", line 306, in init
  File "/tmp/tmpZDBAHx/inql/generators/query.py", line 238, in generate
  File "/tmp/tmpZDBAHx/inql/generators/query.py", line 83, in recurse_fields
  File "/tmp/tmpZDBAHx/inql/generators/query.py", line 83, in recurse_fields
  File "/tmp/tmpZDBAHx/inql/generators/query.py", line 122, in recurse_fields
  File "/tmp/tmpZDBAHx/inql/generators/query.py", line 83, in recurse_fields
  File "/tmp/tmpZDBAHx/inql/generators/query.py", line 72, in recurse_fields
  File "/tmp/tmpZDBAHx/inql/generators/query.py", line 72, in <lambda>
  File "/tmp/tmpZDBAHx/inql/generators/query.py", line 20, in reverse_lookup_order
  File "/tmp/tmpZDBAHx/inql/generators/query.py", line 20, in reverse_lookup_order
TypeError: unicode indices must be integers
```

### Solutions attempted:
- Reloading the extension
- Restarting Burp Suite
- Reinstalling the extension
- Attempt to import json schema

None of the above succeeds.

Is there any fix that can be implemented?

**Comment by execveat** [comment]
Hey there! Could you please help me replicating the issue:

1. Looks like you're running Linux, is it Kali or some other distro? Which release? Is architecture x64 or something else?
2. Did you get the standalone Jython from https://www.jython.org/download.html or some other source?
3. Did you install InQL from BApp Store within the Burp, are you running JAR from https://github.com/doyensec/inql/releases/tag/v5.0.1 or did you build it yourself?

I haven't seen this error, but I'll try to fix it as soon as I manage to replicate it. Thanks for the help.

**Comment by HakuPiku** [comment]
I was having this same issue with the BApp store version. Switching to the latest release on Github fixed the issue.

1) I am on Macbook air (M2).  
2) Standalone from that link -- works for everything else
3)  BApp store version
