### ISSUE TITLE
Permission denied when begins analyze

### ISSUE THREAD

**Issue by kody-black** [doyensec/inql#137]
I downloaded https://github.com/doyensec/inql/releases/download/v5.0.2/InQL.jar as an extension of burp. But when I click"Generate queries with InQL Scanner“, it will pop up an error as shown in the screenshot.

**Error Log**
```
[thread#170 ui.py:34 :: visual_error()]    Got exception and converted it to popup error: '[Errno 13] Permission denied: '111.186.57.85:40472/2024-04-06_150507\\request_template.txt''
[thread#178 introspection.py:132 :: _analyze()]    Failed to create a new directory for the reports '%s' - as it already exists
[thread#178 ui.py:27 :: visual_error()]    Traceback (most recent call last):
  File "__pyclasspath__/inql/scanner/introspection.py", line 70, in analyze
    _analyze(url, filename, headers)
  File "__pyclasspath__/inql/scanner/introspection.py", line 133, in _analyze
    log.debug("Created the directory structure for the '%s'", url)
IOError: [Errno 13] Permission denied: '111.186.57.85:40472/2024-04-06_151126\\request_template.txt'

[thread#178 ui.py:34 :: visual_error()]    Got exception and converted it to popup error: '[Errno 13] Permission denied: '111.186.57.85:40472/2024-04-06_151126\\request_template.txt''
```
**Screenshots**
![image](https://github.com/doyensec/inql/assets/55440303/e9d7aa9f-ff78-4f06-85a6-eb7e1379b34d)

 - OS: Windows 11
 - Java Version:  java 21.0.2 2024-01-16 LTS
- Python Version: Python 3.12.2
- Burp Version: BurpSuite pro V2024.2.1

**Comment by bartek-doyensec** [comment]
We are preparing to release the v6.0 update, which rewrites InQL into Kotlin language. This major update should address the issue, so we are closing it to help clear the backlog.

If you believe this issue still exists in the latest version (v6.0), please feel free to create a new issue.
Thanks!
