### ISSUE TITLE
Repeated TypeError in Burp Scanner Plugin using InQL Extension

### ISSUE THREAD

**Issue by ShanoojM** [doyensec/inql#139]
Dear Support Team,

I am encountering a recurring error within our Burp Scanner plugin, specifically in the inql.traffic_scan.scan_handler.py module. Below is the full error log for reference:

Error Log:
Traceback (most recent call last):
  File "__pyclasspath__/inql/traffic_scan/scan_handler.py", line 236, in doActiveScan
  File "__pyclasspath__/inql/traffic_scan/scan_handler.py", line 134, in _get_matches
TypeError: object of type 'NoneType' has no len()

    at org.python.core.Py.TypeError(Py.java:234)
    at org.python.core.PyObject.__len__(PyObject.java:637)
    at org.python.core.__builtin__.len(__builtin__.java:729)
    ...
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1570)

This error appears to originate in the _get_matches function within scan_handler.py, where a NoneType object is unexpectedly being passed to len(). This is likely due to an uninitialized or failed variable, which is expected to hold a list or string.

The error repeatedly occurs during the execution of the doActiveScan function, which is part of the BurpScannerCheck class, and it impacts multiple threads, as shown in the multi-threaded context (ThreadPoolExecutor). This affects the consistency of the scan results and leads to multiple interruptions in the scan process.

Could you please advise on any potential solutions? Specifically, any insights into the _get_matches function’s handling of NoneType values or guidance on ensuring proper initialization of variables would be very helpful.

Regards,
Shanooj

**Comment by bartek-doyensec** [comment]
We are preparing to release the v6.0 update, which rewrites InQL into Kotlin language. This major update should address the issue, so we are closing it to help clear the backlog.

If you believe this issue still exists in the latest version (v6.0), please feel free to create a new issue.
Thanks!
