### ISSUE TITLE
Using Cookie instead of API Authentication Key in InQL CLI

### ISSUE THREAD

**Issue by vyastj** [doyensec/inql#27]
**Describe the bug**
I am trying to use `InQL CLI` on my corporate GraphQL endpoint. However, I don't have an API authentication key and we authorise via `JSESSIONID`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Using the 'InQL CLI' --> `inql -t https://xyx/endpoint --header 'Cookie: JSESSIONID=xxxx' 'Content-Type: application/json'` (I am using `Content-Type` because it requires second header).

**Output**
```
[!] Invalid header name b'Cookie: Jsessionid=xxxx'
Traceback (most recent call last):
  File "/usr/local/bin/inql", line 4, in <module>
    __import__('pkg_resources').run_script('inql===2.0.0-3-ge821020', 'inql')
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/site-packages/inql-2.0.0_3_ge821020-py3.8.egg/EGG-INFO/scripts/inql", line 9, in <module>
  File "/usr/local/lib/python3.8/site-packages/inql-2.0.0_3_ge821020-py3.8.egg/inql/introspection.py", line 213, in main
  File "/usr/local/lib/python3.8/site-packages/inql-2.0.0_3_ge821020-py3.8.egg/inql/introspection.py", line 277, in init
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

**Expected behaviour**
I am not sure about the error but I think I shouldn’t  be needing to provide a `key "-k"`

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Java Version: java 14.0.1 2020-04-14
                          Java(TM) SE Runtime Environment (build 14.0.1+7)
                          Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
- Python Version: Python 3.8.5

**Additional context**
N/A

**Comment by thypon** [comment]
Ehi, author here!

Header flag syntax is in the following form `--header COOKIE_NAME COOKIE_CONTENT`.
This parameter can be repeated.

```bash
inql -t https://xyx/endpoint \
   --header Cookie 'JSESSIONID=xxxx'
   --header 'Content-Type' 'application/json'
```

**Comment by vyastj** [comment]
Thanks a ton. It worked
