### ISSUE TITLE
OSError: unlink(): an unknown error occurred: __init__.py

### ISSUE THREAD

**Issue by z3dc0ps** [doyensec/inql#28]
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\burp\inql_burp.py", line 45, in <module>
    __stickytape_write_module('''inql/widgets/__init__.py''', '''''')
  File "C:\Users\Administrator\Downloads\burp\jython-standalone-2.7.2.jar\Lib\contextlib.py", line 35, in __exit__
  File "C:\Users\Administrator\Downloads\burp\inql_burp.py", line 14, in __stickytape_temporary_dir
    shutil.rmtree(dir_path)
  File "C:\Users\Administrator\Downloads\burp\jython-standalone-2.7.2.jar\Lib\shutil.py", line 247, in rmtree
  File "C:\Users\Administrator\Downloads\burp\jython-standalone-2.7.2.jar\Lib\shutil.py", line 247, in rmtree
  File "C:\Users\Administrator\Downloads\burp\jython-standalone-2.7.2.jar\Lib\shutil.py", line 252, in rmtree
  File "C:\Users\Administrator\Downloads\burp\jython-standalone-2.7.2.jar\Lib\shutil.py", line 250, in rmtree
OSError: unlink(): an unknown error occurred: C:\Users\Administrator\AppData\Local\Temp\tmphoyoka\inql\actions\__init__.py

	at org.python.core.PyException.doRaise(PyException.java:211)
	at org.python.core.Py.makeException(Py.java:1638)
	at org.python.core.Py.makeException(Py.java:1642)
	at org.python.core.Py.makeException(Py.java:1646)
	at org.python.core.Py.makeException(Py.java:1650)
	at contextlib$py.__exit__$4(C:/Users/Administrator/Downloads/burp/jython-standalone-2.7.2.jar/Lib/contextlib.py:51)
	at contextlib$py.call_function(C:/Users/Administrator/Downloads/burp/jython-standalone-2.7.2.jar/Lib/contextlib.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:187)
	at org.python.core.PyFunction.__call__(PyFunction.java:449)
	at org.python.core.PyMethod.__call__(PyMethod.java:171)
	at org.python.core.ContextGuard.__exit__(ContextGuard.java:29)
	at org.python.pycode._pyx4.f$0(C:/Users/Administrator/Downloads/burp/inql_burp.py:79)
	at org.python.pycode._pyx4.call_function(C:/Users/Administrator/Downloads/burp/inql_burp.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:287)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.ar4.<init>(Unknown Source)
	at burp.c2x.a(Unknown Source)
	at burp.cyy.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
![1](https://user-images.githubusercontent.com/61974788/100568058-145b4e00-32f0-11eb-9710-2c545df1fac8.PNG)

**Comment by z3dc0ps** [comment]
The Error got in v3.0.0.
v2.0.0 is loaded successfully.
![1](https://user-images.githubusercontent.com/61974788/100568177-774ce500-32f0-11eb-8029-7619a9cb1d15.PNG)

**Comment by thypon** [comment]
```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 16.04, Windows 10, macOS Catalina]
 - Java Version: [e.g. java -v output, if applicable]
- Python Version: [e.g. Jython v2.7.0/Python 3.4.3]
- Burp Version: [eg. 2.1.0 if applicable]
 - Version: [e.g. 22]

**Additional context**
Add any other context about the problem here.
```

We have a format for troubleshooting the issues: can you fill all the fields?

Unlink is usually related to unloading. Cannot reproduce the issue if I don't know what it is.

**Comment by z3dc0ps** [comment]
**Describe the bug**

OSError: unlink(): an unknown error occurred: __init__.py while loading burp extension

**To Reproduce**

Steps to reproduce the behavior:
1. Download New version of inql from <a href="https://github.com/doyensec/inql/releases/tag/v3.0.0">Here</a>
2. Go to Burpsuite and load jython 
3. add inql_burp.py in burpsuite
4. See error

**Expected behavior**

The Error occurs only in v3.0.0 , the v2.0.0 is loaded successfully

**Screenshots**

Screenshot and video are attached 

**Desktop (please complete the following information):**

 - OS: [ Windows 10]
 - Java Version: [java 15 2020-09-15]
- Python Version: [Python 3.9.0]
- Burp Version: [eg. 2.1.0 if applicable]
 - Version: [Burp suite v2020.11.2]

![1](https://user-images.githubusercontent.com/61974788/100694730-aaa57780-33b5-11eb-9bdc-f2aba22dc971.PNG)

[inql.zip](https://github.com/doyensec/inql/files/5620168/inql.zip)

**Comment by ruvlol** [comment]
Same issue here

**Comment by thypon** [comment]
Hi there, I uploaded a new release with a fixed stickytape version, can you please test it? 

https://github.com/doyensec/inql/releases/download/v3.0.0/inql_burp.py

**Comment by ruvlol** [comment]
It fixed the issue to me. Thank you

**Comment by irsdl** [comment]
I am using version 4.0.5 in Windows 10 with Jython 2.7.2 and the latest Burp Pro early adaptor version (2021.12.1). After my burp suite process (Java) was killed accidentally, I now have the same error when trying to load this extension.

If I wait for a few minutes and then try to reload it then the issue will go away. It tells me the issue comes from line 14 of `inql_burp.py`:

```
shutil.rmtree(dir_path)
```

![image](https://user-images.githubusercontent.com/1798313/149501309-e4b76bf4-a774-4d28-aa39-5dc67e5fb53e.png)

**Comment by rafaelfini** [comment]
same as @irsdl with exact same set up

**Comment by thypon** [comment]
That's not the same issue, and should be treated in a separated issue. The original issue reported was due to a custom `stickytape` employed, this other is due to crashing Burp.

Please fill an appropriate issue following the issue template, to identify the issue correctly!
