### ISSUE TITLE
load extensions failed

### ISSUE THREAD

**Issue by prohk** [doyensec/inql#33]
**Describe the bug**
when i try to load the extensions , some error occurred and i can't figure it out :
![image](https://user-images.githubusercontent.com/37725167/115374500-7ebd4e00-a1ff-11eb-9821-b9a8f1ba6d3c.png)

the errors:
Traceback (most recent call last):
  File "C:\Users\J\AppData\Roaming\BurpSuite\bapps\296e9a0730384be4b2fffef7b4e19b1f\ext\inql_burp.py", line 76, in <module>
    if platform.system() == "Java":
  File "F:\ç½é¡µä¸è½½\jython-standalone-2.7.1.jar\Lib\platform.py", line 1396, in system
  File "F:\ç½é¡µä¸è½½\jython-standalone-2.7.1.jar\Lib\platform.py", line 1213, in uname
	at org.python.core.PyString.<init>(PyString.java:57)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.core.PyString.<init>(PyString.java:74)
	at org.python.core.Py.newString(Py.java:647)
	at org.python.modules.posix.PosixModule.uname(PosixModule.java:1173)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value

	at org.python.core.PyException.doRaise(PyException.java:205)
	at org.python.core.Py.makeException(Py.java:1565)
	at org.python.core.Py.makeException(Py.java:1569)
	at org.python.core.Py.makeException(Py.java:1573)
	at org.python.core.Py.makeException(Py.java:1577)
	at org.python.pycode._pyx5.f$0(C:\Users\J\AppData\Roaming\BurpSuite\bapps\296e9a0730384be4b2fffef7b4e19b1f\ext\inql_burp.py:77)
	at org.python.pycode._pyx5.call_function(C:\Users\J\AppData\Roaming\BurpSuite\bapps\296e9a0730384be4b2fffef7b4e19b1f\ext\inql_burp.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at burp.fnl.<init>(Unknown Source)
	at burp.fm9.a(Unknown Source)
	at burp.fl5.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win10
 - Java Version: jdk1.6
- Python Version: python 3.8
- Burp Version: 2021.4

**Additional context**

**Comment by prohk** [comment]
update the errors:
Traceback (most recent call last):
  File "F:\burp-extent\inql_burp.py", line 76, in <module>
    if platform.system() == "Java":
  File "F:\jython\Lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "F:\burp-extent\inql_burp.py", line 14, in __stickytape_temporary_dir
    shutil.rmtree(dir_path)
  File "F:\jython\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "F:\jython\Lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "F:\jython\Lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: unlink(): an unknown error occurred: C:\Users\J\AppData\Local\Temp\tmpoz1vm7\burp_ext\__init__.py

	at org.python.core.PyException.doRaise(PyException.java:205)
	at org.python.core.Py.makeException(Py.java:1565)
	at org.python.core.Py.makeException(Py.java:1569)
	at org.python.core.Py.makeException(Py.java:1573)
	at org.python.core.Py.makeException(Py.java:1577)
	at contextlib$py.__exit__$4(F:\jython\Lib\contextlib.py:51)
	at contextlib$py.call_function(F:\jython\Lib\contextlib.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:189)
	at org.python.core.PyFunction.__call__(PyFunction.java:446)
	at org.python.core.PyMethod.__call__(PyMethod.java:171)
	at org.python.core.ContextGuard.__exit__(ContextGuard.java:29)
	at org.python.pycode._pyx4.f$0(F:\burp-extent\inql_burp.py:77)
	at org.python.pycode._pyx4.call_function(F:\burp-extent\inql_burp.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at burp.fnl.<init>(Unknown Source)
	at burp.fm9.a(Unknown Source)
	at burp.fl5.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
thinks for help.

**Comment by thypon** [comment]
The error does not seem to be related to `inql` but to `jython`. I  will perform some tests, but the stacktrace seems to clearly indicate that jython does not support being stored in directories containing UTF-8 or special encoding characters.

Please feel free to reopen if the proposed fix does not help you.
