### ISSUE TITLE
Error on loading [undisclosed] endpoint.

### ISSUE THREAD

**Issue by Techbrunch** [doyensec/inql#34]
When loading a GraphQL API the plugin crashes, the introspection query works I can see it in the logger.

```
Traceback (most recent call last):
  File "/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmp1MdcO6/burp_ext/extender.py", line 45, in registerExtenderCallbacks
  File "/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmp1MdcO6/inql/burp_ext/timer_tab.py", line 35, in __init__
  File "/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmp1MdcO6/inql/widgets/timer.py", line 62, in __init__
TypeError: javax.swing.JComboBox(): 1st arg can't be coerced to java.util.Vector, java.lang.Object[], javax.swing.ComboBoxModel

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyReflectedFunction.throwError(PyReflectedFunction.java:209)
	at org.python.core.PyReflectedFunction.throwBadArgError(PyReflectedFunction.java:312)
	at org.python.core.PyReflectedFunction.throwError(PyReflectedFunction.java:321)
	at org.python.core.PyReflectedConstructor.__call__(PyReflectedConstructor.java:177)
	at org.python.core.PyObject.__call__(PyObject.java:419)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:19)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:1713)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at inql.widgets.timer$py.__init__$2(/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmp1MdcO6/inql/widgets/timer.py:95)
	at inql.widgets.timer$py.call_function(/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmp1MdcO6/inql/widgets/timer.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyFunction.__call__(PyFunction.java:476)
	at org.python.core.PyInstance.__init__(PyInstance.java:124)
	at org.python.core.PyClass.__call__(PyClass.java:193)
	at org.python.core.PyObject.__call__(PyObject.java:394)
	at inql.burp_ext.timer_tab$py.__init__$2(/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmp1MdcO6/inql/burp_ext/timer_tab.py:35)
	at inql.burp_ext.timer_tab$py.call_function(/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmp1MdcO6/inql/burp_ext/timer_tab.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:19)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:1713)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.PyObject.__call__(PyObject.java:478)
	at org.python.core.PyObject.__call__(PyObject.java:482)
	at burp_ext.extender$py.registerExtenderCallbacks$2(/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmp1MdcO6/burp_ext/extender.py:47)
	at burp_ext.extender$py.call_function(/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmp1MdcO6/burp_ext/extender.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.burp_ext.extender$BurpExtender$27.registerExtenderCallbacks(Unknown Source)
	at burp.h1k.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Traceback (most recent call last):
  File "/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmp1MdcO6/inql/burp_ext/timer_tab.py", line 98, in processHttpMessage
AttributeError: 'TimerTab' object has no attribute 'panel'

	at org.python.core.Py.AttributeError(Py.java:205)
	at org.python.core.PyObject.noAttributeError(PyObject.java:1013)
	at org.python.core.PyObject.__getattr__(PyObject.java:1008)
	at inql.burp_ext.timer_tab$py.processHttpMessage$12(/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmp1MdcO6/inql/burp_ext/timer_tab.py:98)
	at inql.burp_ext.timer_tab$py.call_function(/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmp1MdcO6/inql/burp_ext/timer_tab.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.inql.burp_ext.timer_tab$TimerTab$25.processHttpMessage(Unknown Source)
	at burp.am6.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

**Desktop:**

- OS: macOS Big Sur
- Python Version: Jython v2.7.0
- Burp Version: 2021.5.1
 - Version: 3.1.0

**Comment by Techbrunch** [comment]
Hi thypon, with jython 2.7.2 I have another error:

```
Exception in thread Thread-2:Traceback (most recent call last):
  File "/Applications/jython-standalone-2.7.2.jar/Lib/threading.py", line 222, in _Thread__bootstrap
    self.run()
  File "/Applications/jython-standalone-2.7.2.jar/Lib/threading.py", line 213, in run
    self._target(*self._args, **self._kwargs)
  File "/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmpjJzBAH/inql/utils.py", line 159, in async_run
  File "/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmpjJzBAH/inql/widgets/generator.py", line 312, in async_run
  File "/var/folders/rn/8g3wbky125nghvbyw9whlt3r0000gn/T/tmpjJzBAH/inql/introspection.py", line 281, in init
  File "/Applications/jython-standalone-2.7.2.jar/Lib/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Applications/jython-standalone-2.7.2.jar/Lib/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer, but got <type 'NoneType'>
```

**Comment by Techbrunch** [comment]
Hum you are right now I don't have any error but nothing is loaded. I tried manually loading the json and it works.

I think it might be the size of the response the problem: 893299.

I can't share the URL publicly, is there a way to send it to you privatly ?

**Comment by thypon** [comment]
github[at]pompel[dot]me should be fine

**Comment by thypon** [comment]
Mh @Techbrunch I tested the endpoint you provided and it is outputting the analysis immediately. Are you enabling cycles detection? There may be a timeout/race condition with super connected graphs with that option enabled, which is not on by default anyway.

**Comment by Techbrunch** [comment]
FYI I'm using the Burp Suite plugin and not the standalone client, if that's what you tried then you can just close the issue.

**Comment by thypon** [comment]
Indeed, tested on latest machine. I think it was a transient condition due timing.

Feel free to reopen if you think the bug is still there.
