### ISSUE TITLE
HTTP/2 issues

### ISSUE THREAD

**Issue by DemanNL** [doyensec/inql#35]
I was unable to get a GraphQL scan for the following URL working:
https://api.myactions.eu/graphql

However, after disabling HTTP/2 support in Burp it suddenly works.

The following error is given in the plugin error log which might be related:
```Exception in thread Thread-2:Traceback (most recent call last):
  File "/opt/BurpSuitePro/jython-standalone-2.7.2.jar/Lib/threading$py.class", line 222, in _Thread__bootstrap
    self.run()
  File "/opt/BurpSuitePro/jython-standalone-2.7.2.jar/Lib/threading$py.class", line 213, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/tmpyNUu2x/inql/utils.py", line 159, in async_run
  File "/tmp/tmpyNUu2x/inql/widgets/generator.py", line 312, in async_run
  File "/tmp/tmpyNUu2x/inql/introspection.py", line 281, in init
  File "/opt/BurpSuitePro/jython-standalone-2.7.2.jar/Lib/json/__init__$py.class", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/BurpSuitePro/jython-standalone-2.7.2.jar/Lib/json/decoder$py.class", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer, but got <type 'NoneType'>```

As for now disabling HTTP/2 seems to be needed to make the InQL plugin work.

**Comment by thypon** [comment]
```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 16.04, Windows 10, macOS Catalina]
 - Java Version: [e.g. java -v output, if applicable]
- Python Version: [e.g. Jython v2.7.0/Python 3.4.3]
- Burp Version: [eg. 2.1.0 if applicable]
 - Version: [e.g. 22]

**Additional context**
Add any other context about the problem here.
```

Indeed, can you please specify the information as requested in the Bug Report template.
This is not only a known issue, but an issue already addressed in the latest public release.

https://github.com/doyensec/inql/commit/f05bcd3a2aaf5d823ec50a727fc3d97e36d788f3

Feel free to reopen if you feel the issue still affects you after upgrading to 4.0.1.
